/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ImageRescalerJNI */

#ifndef _Included_ImageRescalerJNI
#define _Included_ImageRescalerJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ImageRescalerJNI
 * Method:    rescaleImage
 * Signature: ([S[BIII)V
 */
JNIEXPORT void JNICALL Java_ImageRescalerJNI_rescaleImage
  (JNIEnv *, jobject, jshortArray, jbyteArray, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
